name: GitHub Pages Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-deployment
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.page-deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4
      
      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      
      - name: Deploy static content
        id: page-deploy
        uses: actions/deploy-pages@v4
